server:
  port: 8080

spring:
  application:
    name: producer-app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 131072
      properties:
        linger.ms: 50

app:
  kafka:
    topic: group-demo-topic
    partitions: 4
